# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingvalue',
            name='charging_station',
        ),
        migrations.RemoveField(
            model_name='chargingvalue',
            name='rfid',
        ),
        migrations.RemoveField(
            model_name='rfid',
            name='flat',
        ),
        migrations.DeleteModel(
            name='ChargingStation',
        ),
        migrations.DeleteModel(
            name='ChargingValue',
        ),
        migrations.DeleteModel(
            name='RFID',
        ),
    ]
