# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcs', '0003_auto_20170701_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvalue',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='end_value',
            field=models.FloatField(blank=True),
        ),
    ]
