# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcs', '0004_auto_20170702_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvalue',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='end_value',
            field=models.FloatField(null=True),
        ),
    ]
