# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evcs', '0005_auto_20170702_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='flat',
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='charging_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmetering.Flat'),
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='rfid',
            field=models.CharField(max_length=30, verbose_name='RFID'),
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chargingvalue',
            name='start_value',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='ChargingStation',
        ),
        migrations.DeleteModel(
            name='RFID',
        ),
    ]
